name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install libuv
      run: sudo apt install -y libuv1-dev
    - name: install boost
      run: sudo apt install -y libboost1.81-dev
    - name: make
      run: |
        mkdir build && cd build
        cmake -DWITH_NUMA=OFF ..
        make
