name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt install -y libboost-all-dev
    - name: install libuv
      run: sudo apt install -y libuv
    - name: make
      run: |
        mkdir build && cd build
        cmake ..
        make
