name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt install -y libboost-all-dev
    - name: build bir
      run: mkdir build & cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
